import { useState } from 'react';
import { Pencil, Plus, Tag, Trash2 } from 'lucide-react';
import { useInventory } from '../context/InventoryContext';
import { useToast } from '../context/ToastContext';
import Modal from '../components/common/Modal';
import ConfirmDialog from '../components/common/ConfirmDialog';
import LoadingState from '../components/common/LoadingState';
import EmptyState from '../components/common/EmptyState';

export default function Categories() {
  const { categories, products, addCategory, editCategory, removeCategory, loading } = useInventory(); const { showToast } = useToast();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [deleteTarget, setDeleteTarget] = useState(null); const [busy, setBusy] = useState(false);
  const start = (category = null) => { setEditing(category); setName(category?.name || ''); setError(''); setOpen(true); };
  const submit = async (event) => { event.preventDefault(); if (!name.trim()) return setError('Category name is required.'); setBusy(true); try { if (editing) await editCategory(editing.id, name); else await addCategory(name); setOpen(false); showToast(editing ? 'Category updated.' : 'Category created.'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const remove = async () => { try { await removeCategory(deleteTarget.id, deleteTarget.name); showToast('Category deleted.'); } catch (err) { showToast(err.message, 'error'); } setDeleteTarget(null); };
  if (loading) return <LoadingState label="Loading categories..." />;
  return <div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">Categories</h1><p className="text-sm text-slate-500 mt-1">Organize products into easy-to-scan groups.</p></div><button className="btn-primary" onClick={() => start()}><Plus className="w-4 h-4" />Add category</button></div>{categories.length === 0 ? <EmptyState icon={Tag} title="No categories yet" description="Create your first category to organize products." /> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{categories.map((category) => <div className="card p-5" key={category.id}><div className="flex items-start justify-between"><div className="p-2 rounded-md bg-primary-50 dark:bg-primary-900/20 text-primary-600"><Tag className="w-5 h-5" /></div><div className="flex gap-1"><button className="btn-ghost p-2" title="Edit category" onClick={() => start(category)}><Pencil className="w-4 h-4" /></button><button className="btn-ghost p-2 text-red-500" title="Delete category" onClick={() => setDeleteTarget(category)}><Trash2 className="w-4 h-4" /></button></div></div><h2 className="font-semibold mt-4">{category.name}</h2><p className="text-sm text-slate-500 mt-1">{products.filter((product) => product.category === category.name).length} products</p></div>)}</div>}<Modal isOpen={open} onClose={() => setOpen(false)} title={editing ? 'Edit category' : 'Add category'}><form onSubmit={submit} className="space-y-4">{error && <p className="error-text">{error}</p>}<label className="block"><span className="label">Category name *</span><input className="input" autoFocus value={name} onChange={(e) => { setName(e.target.value); setError(''); }} /></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? 'Saving...' : 'Save category'}</button></div></form></Modal><ConfirmDialog isOpen={deleteTarget !== null} onClose={() => setDeleteTarget(null)} onConfirm={remove} title="Delete category?" message="Categories assigned to products cannot be deleted." confirmLabel="Delete category" /></div>;
}
