import { useEffect, useState } from 'react';
import { Bell, Moon, Save, Store } from 'lucide-react';
import { useInventory } from '../context/InventoryContext';
import { useToast } from '../context/ToastContext';
import LoadingState from '../components/common/LoadingState';

export default function Settings() {
  const { settings, updateAppSettings, loading } = useInventory(); const { showToast } = useToast(); const [form, setForm] = useState(settings); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => setForm(settings), [settings]);
  if (loading || !form) return <LoadingState label="Loading settings..." />;
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); if (!form.businessName.trim() || !form.ownerName.trim() || Number(form.lowStockThreshold) < 0) return setError('Enter a business name, owner name, and a valid stock threshold.'); setBusy(true); try { await updateAppSettings({ ...form, lowStockThreshold: Number(form.lowStockThreshold) }); showToast('Settings saved.'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="max-w-3xl space-y-5"><div><h1 className="text-xl font-semibold">Settings</h1><p className="text-sm text-slate-500 mt-1">Configure the workspace for your business.</p></div><form onSubmit={submit} className="card p-5 sm:p-7 space-y-7">{error && <div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}<section><div className="flex items-center gap-2 mb-4"><Store className="w-5 h-5 text-primary-600" /><h2 className="font-semibold">Business profile</h2></div><div className="grid sm:grid-cols-2 gap-4"><label className="block"><span className="label">Business name *</span><input className="input" value={form.businessName} onChange={(e) => update('businessName', e.target.value)} /></label><label className="block"><span className="label">Owner name *</span><input className="input" value={form.ownerName} onChange={(e) => update('ownerName', e.target.value)} /></label></div></section><section className="border-t border-slate-200 dark:border-slate-800 pt-6"><h2 className="font-semibold mb-4">Inventory preferences</h2><div className="grid sm:grid-cols-2 gap-4"><label className="block"><span className="label">Currency</span><select className="input" value={form.currency} onChange={(e) => update('currency', e.target.value)}><option value="USD">USD ($)</option><option value="EUR">EUR (€)</option><option value="GBP">GBP (£)</option><option value="PKR">PKR (Rs)</option></select></label><label className="block"><span className="label">Low-stock threshold</span><input className="input" type="number" min="0" value={form.lowStockThreshold} onChange={(e) => update('lowStockThreshold', e.target.value)} /></label></div></section><section className="border-t border-slate-200 dark:border-slate-800 pt-6 space-y-4"><h2 className="font-semibold mb-4">Preferences</h2><Toggle icon={Moon} label="Dark mode" checked={form.darkMode} onChange={(value) => update('darkMode', value)} /><Toggle icon={Bell} label="Low-stock notifications" checked={form.notifications} onChange={(value) => update('notifications', value)} /></section><div className="flex justify-end border-t border-slate-200 dark:border-slate-800 pt-5"><button className="btn-primary" disabled={busy}><Save className="w-4 h-4" />{busy ? 'Saving...' : 'Save settings'}</button></div></form></div>;
}

function Toggle({ icon: Icon, label, checked, onChange }) { return <label className="flex items-center justify-between gap-4 cursor-pointer"><span className="flex items-center gap-2 text-sm"><Icon className="w-4 h-4 text-slate-400" />{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /></label>; }
